name: Weekly Options Screener
on:
  schedule:
    - cron: '0 13 * * 1' # Runs every Monday at 8 AM EST
  workflow_dispatch: # Allows manual "Run workflow" button

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # We add html5lib and beautifulsoup4 as backup parsers
          pip install yfinance scipy pandas requests lxml html5lib beautifulsoup4

      - name: Run screener
        env:
          FINNHUB_KEY: ${{ secrets.FINNHUB_KEY }}
        run: python screener.py

      - name: Upload CSV Results
        uses: actions/upload-artifact@v4
        with:
          name: Whale-Report
          path: Options_Whale_Screen_2026.csv


